version: '3.8'

services:
  ca-orders-api:
    build: .
    container_name: ca-orders-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
      - wiremock-payment
      - wiremock-fulfillment
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ca_order_api?reWriteBatchedInserts=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PAYMENT_BASE_URL: http://wiremock-payment:8080
      FULFILLMENT_BASE_URL: http://wiremock-fulfillment:8080

  postgres:
    image: postgres:16
    container_name: ca-order-api-postgres
    environment:
      POSTGRES_DB: ca_order_api
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: ca-order-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Create TWO entry points: INTERNAL and EXTERNAL for local build
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  wiremock-payment:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock-payment
    ports:
      - "8089:8080"
    volumes:
      - ./mock/wiremock/payment:/home/wiremock
    command: [ "--global-response-templating", "--verbose" ]

  wiremock-fulfillment:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock-fulfillment
    ports:
      - "8090:8080"
    volumes:
      - ./mock/wiremock/fulfillment:/home/wiremock
    command: [ "--global-response-templating", "--verbose" ]

volumes:
  pgdata:
  redisdata: