spring:
  application:
    name: ca-orders-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ca_order_api?reWriteBatchedInserts=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ca_order_api
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: ca-orders-hikari-pool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    default-schema: ca_order_api
    enabled: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    topic:
      order-event: order-events

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        retries: 5

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.caorderapi.kafka.model
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.caorderapi.kafka.model.OrderEvent

logging:
  level:
    com.caorderapi: INFO
    org.hibernate.SQL: INFO

resilience4j:
  circuitbreaker:
    instances:
      paymentClient:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 5
      fulfillmentClient:
        slidingWindowSize: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 20000

app:
  payment:
    base-url: ${PAYMENT_BASE_URL:http://localhost:8089}

  fulfillment:
    base-url: ${FULFILLMENT_BASE_URL:http://localhost:8090}

  orders:
    initial-status: PENDING
    pay-target-status: PAID
    fulfill-target-status: FULFILLED
    cancelled-status: CANCELLED
    reservation-ttl-minutes: 15
  order-items:
    initial-status: PENDING
    pay-target-status: CONFIRMED
    fulfill-target-status: FULFILLED
    cancelled-status: CANCELLED

  jobs:
    outbox-publish-delay-ms: 2000
    pending-order-cancellation-ms: 5000


